package mocks

import "github.com/stretchr/testify/mock"

// FakeSet is an autogenerated mock type for the FakeSet type
type FakeSet struct {
	mock.Mock
}

// Execute provides a mock function with given fields: source, field, value
func (_m *FakeSet) Execute(source any, field string, value any) error {
	ret := _m.Called(source, field, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(any, string, any) error); ok {
		r0 = rf(source, field, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSet interface {
	mock.TestingT
	Cleanup(func())
}

// NewFakeSet creates a new instance of FakeSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFakeSet(t mockConstructorTestingTNewSet) *FakeSet {
	fakeSet := &FakeSet{}
	fakeSet.Mock.Test(t)

	t.Cleanup(func() { fakeSet.AssertExpectations(t) })

	return fakeSet
}
